<?php
$sstr=array(
':)',
':(',
';)',
':-P',
'=-O',
':-[',
'.daun.',
'.gy.',
'.zzz.',
'.ura.',
'.ninja.',
'.welcome.',
'.pardon.',
'.hi.',
'.read.',
'.unsure.',
'.victory.',
'.secret.',
'.inlove.',
'^^',
'.vis.',
'.tus.',
'.gitara.',
'.nunu.',
'.banan.',
'.joke.',
'.elka.',
'.flood.',
'.spam.',
'хуй'
);
$simg=array(
'<img src="sm/smile2.gif" alt=":)"/>',
'<img src="sm/sad2.gif" alt=":("/>',
'<img src="sm/wink2.gif" alt=";)"/>',
'<img src="sm/tongue2.gif" alt=":-P"/>',
'<img src="sm/shok2.gif" alt="=-O"/>',
'<img src="sm/blush2.gif" alt=":-["/>',
'<img src="sm/gy.gif" alt="daun"/>',
'<img src="sm/angel2.gif" alt="O:)"/>',
'<img src="sm/zzz.gif" alt="zzz"/>',
'<img src="sm/ura.gif" alt="ura"/>',
'<img src="sm/ninja.gif" alt="ninja"/>',
'<img src="sm/welcome.gif" alt="welcome"/>',
'<img src="sm/hi.gif" alt="hi"/>',
'<img src="sm/pardon.gif" alt="pardon"/>',
'<img src="sm/read.gif" alt="read"/>',
'<img src="sm/unsure.gif" alt="unsure"/>',
'<img src="sm/victory.gif" alt="victory"/>',
'<img src="sm/secret.gif" alt="secret"/>',
'<img src="sm/inlove.gif" alt="inlove"/>',
'<img src="sm/shy.gif" alt="^^"/>',
'<img src="sm/vis.gif" alt="vis"/>',
'<img src="sm/tus.gif" alt="tus"/>',
'<img src="sm/gitara.gif" alt="gitara"/>',
'<img src="sm/nunu.gif" alt="nunu"/>',
'<img src="sm/banan.gif" alt="banan"/>',
'<img src="sm/joke.gif" alt="joke"/>',
'<img src="sm/elka.gif" alt="elka"/>',
'<img src="sm/flood.gif" alt="flood"/>',
'<img src="sm/spam.gif" alt="spam"/>',
'<img src="sm/huy.gif" alt="censored"/>',
);
?>
